### ISSUE TITLE
error

### ISSUE THREAD

**Issue by good-demo** [MungoMeng/Registration-NICE-Trans#1]
Thanks for your job.
I encountered the following issue when running your code.
TypeError: descriptor 'decode' for 'bytes' objects doesn't apply to a 'numpy.ndarray' object
Can you provide your requirements.txt

**Comment by MungoMeng** [comment]
Hi, thanks for your interest on our work!

I guess you met this error in the datagenerators.py.
First, there is no need to strictly follow the code of our datagenerator part -- it's highly self-defined based on specific data structure and type. I suggest you just use our core code in network.py and embed it into your own code.

In our dataset setting, there should be a 'train_pairs.npy'/'valid_pairs.npy'/'test_pair.npy' in the data path, which include the image paris used for training/validation/testing, such as [[filename_2, filename_34], [filename_23, filename_4], [filename_6, filename_12], ...]. The function 'bytes.decode()' was used to convert the filename in the UTF-8 coding. If your filename is not in the UTF-8 coding, you can simply try to remove this function.
