### ISSUE TITLE
作者你好，想问一下数据集的处理细节

### ISSUE THREAD

**Issue by Pull2MAX** [MungoMeng/Registration-NICE-Trans#4]
- 你说你用的七个数据集，四个训练，三个测试，那么这些数据都要裁剪和归一化的，这两个操作我能理解，但是每一个获得的数据spacing和label都是不一样的，这个是怎么处理的呢？还有数据集的label是怎么处理的，希望你能回答一下，谢谢！

**Comment by MungoMeng** [comment]
把所有数据都resample并affine对齐到MNI-152 brain template，用FLIRT库就行。处理完以后所有的图片都和MNI-152模版保持一致的spacing和位置，然后再按照固定的像素位置croping。label也和图片一样做同样的操作就行，用同样affine matrix来进行与图片一致的变换。
训练集的图片是不需要label的，只需要图片做无监督训练。测试集的需要label来评估，但是并不会垮数据集评估。测试是配准同一个数据集内的两张图片，同一个数据集下label的标准是一样的。

**Comment by Pull2MAX** [comment]
谢谢博主，看了你的几个论文，你train的数据集比较独特，谢谢回复，我去试试。

**Comment by MungoMeng** [comment]
其实没必要跟我的数据集，现在不流行这样做了。我是19年跟Voxelmorph的论文准备数据集的，他们也是搞了个大数据集，很难处理的。现在其实流行拿那种处理好的well-benchmark的数据集了。

**Comment by wangsh7** [comment]
> 其实没必要跟我的数据集，现在不流行这样做了。我是19年跟Voxelmorph的论文准备数据集的，他们也是搞了个大数据集，很难处理的。现在其实流行拿那种处理好的well-benchmark的数据集了。

请问有什么推荐的吗，刚开始学习的小白想跑一跑您的代码

**Comment by MungoMeng** [comment]
https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration
建议跟着这个项目作为开始吧，有完整代码框架+数据。我的核心代码在network.py里面，也可以轻松的用在transmorph的代码框架里面的。

**Comment by wangsh7** [comment]
> https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration 建议跟着这个项目作为开始吧，有完整代码框架+数据。我的核心代码在network.py里面，也可以轻松的用在transmorph的代码框架里面的。

太感谢大佬的回复了，提前祝您新的一年生活顺利，平安喜乐，节节高升！

**Comment by bestJeff2048** [comment]
> 把所有数据都resample并affine对齐到MNI-152 brain template，用FLIRT库就行。处理完以后所有的图片都和MNI-152模版保持一致的spacing和位置，然后再按照固定的像素位置croping。label也和图片一样做同样的操作就行，用同样affine matrix来进行与图片一致的变换。
> 训练集的图片是不需要label的，只需要图片做无监督训练。测试集的需要label来评估，但是并不会垮数据集评估。测试是配准同一个数据集内的两张图片，同一个数据集下label的标准是一样的。
-----------------------------------------------------------------------------------------------------------
孟老师你好，请问一下您说的对齐指的是写一个FLIRT库的脚本将所有的脑子数据affine+rigid到MNI-152 brain template吗？

**Comment by Pull2MAX** [comment]
> 您说的对齐指的是写一个FLIRT库的脚本将所有的脑

建议用别人处理好的，还有就是我看大家提到的最多的就是同freesufer去做的，然后对齐到这个mni空间
